name : Build and Deploy Code
on : [push,pull_request]
jobs:
  job1:
    runs-on : ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: echoing build
        run: echo "Cloned the Repo Succesfully" 
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install Python
        run: echo "Python is installed Succesfully" 
      - name: Installing Requirements
        run: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - name: Installing Requiremets
        run: echo "Install All Requiremet Succesfully"