name : Build and Deploy Code
on : [push,pull_request]
jobs:
  build:
    runs-on : ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: echoing build
        run: echo "Cloned the Repo Succesfully" 
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install Python
        run: echo "Python is installed Succesfully" 
      - name: Installing Requirements
        run: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - name: Installing Requirements
        run: echo "Install All Requirement Succesfully"
      - name: Instilling DOcker
        run: docker-compose up --build
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/projectmng:latest